### ISSUE TITLE
Problems with constructor

### ISSUE THREAD

**Issue by char0n** [niksy/babel-plugin-native-error-extend#1]
The plugin works unless 

```js
export class NotImplementedError extends Error {
  constructor(message = 'test') {
    super(message);
  }
}
```

This causes the plugin to go crazy.

```
TypeError: @babel/template placeholder "MESSAGE": Property arguments[0] of NewExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got "AssignmentPattern"
```

**Comment by niksy** [comment]
PR welcome!

**Comment by char0n** [comment]
Sure it is. https://github.com/bjyoungblood/es6-error it is then.

**Comment by niksy** [comment]
@char0n I can’t decide if your tone is passive aggresive or you’re just being rude.

Requesting PR for change is common open source practice where you can take burden off other peoples work and contribute to community. You’re welcome to ignore it, but being rude is not polite and doesn’t help anyone.

Still, I’ve taken time to make the change and pushed new version.

**Comment by char0n** [comment]
> I can’t decide if your tone is passive aggresive or you’re just being rude.

Neither. I have a bussy day and I understood your message in a following way: "If you want to have it fixed, do it yourself". As I'm realistic about my time capabilities I've acknowledged that I don't have a time for this and closed the ticket and suggested a workaround which is quick and works. It wasn't personal in any way.

> Still, I’ve taken time to make the change and pushed new version.

Will the new version scale for 
```js
export class NotImplementedError extends Error {
  constructor(message = 'test', cause) {
    super(message);
    this.cause = cause;
  }
}
```
I suspect the change is very specific and will not compensate for `vararg`  cases.

**Comment by niksy** [comment]
> Neither. I have a bussy day and I understood your message in a following way: "If you want to have it fixed, do it yourself". As I'm realistic about my time capabilities I've acknowledged that I don't have a time for this and closed the ticket and suggested a workaround which is quick and works. It wasn't personal in any way.

Sorry, my intention wasn’t to pass this onto others in rude way. And sorry for misinterpreting your reply!

> Will the new version scale for
> 
> ```js
> export class NotImplementedError extends Error {
>   constructor(message = 'test', cause) {
>     super(message);
>     this.cause = cause;
>   }
> }
> ```
> 
> I suspect the change is very specific and will not compensate for `vararg` cases.

It will, only first parameter is passed on to native `Error` class since it’s the only argument it can receive ([as per documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error)). Everything else you need to set yourself (`cause` in your case). If you can give me example where this is different in native implementation, I will make change.

**Comment by char0n** [comment]
> Sorry, my intention wasn’t to pass this onto others in rude way. And sorry for misinterpreting your reply!

I'm sorry too. Let's forget about this one and move forward ;]

> It will, only first parameter is passed on to native Error class since it’s the only argument it can receive (as per documentation). Everything else you need to set yourself (cause in your case). If you can give me example where this is different in native implementation, I will make change.

Sounds cool. Checking in my local codebase.

**Comment by char0n** [comment]
I confirm that it works as expected. Thanks for this lib and your work!

**Comment by niksy** [comment]
Glad it works!
