### ISSUE TITLE
Problem when simple class is introduced

### ISSUE THREAD

**Issue by char0n** [niksy/babel-plugin-native-error-extend#2]
Hi,

I've intercepted a problem with the plugin when using the plugin to transpile the following code:

```js
class Test { } 
```

This results in 
```
TypeError: file.js: Cannot read property 'name' of null
    at PluginPass.ClassDeclaration (node_modules/babel-plugin-native-error-extend/cjs/index.js:31:46)
```

**Comment by niksy** [comment]
@char0n Ah yes, I see. Plugin didn’t handle cases where there isn’t any class extending. Pushed in new version!

**Comment by char0n** [comment]
Thanks for the work!

I can verify that the issue is gone now.
