### ISSUE TITLE
Support second parameter

### ISSUE THREAD

**Issue by niksy** [niksy/babel-plugin-native-error-extend#3]
Add support for second parameter (e.g error cause): https://2ality.com/2021/06/error-cause.html#consequence-for-your-own-code

**Comment by char0n** [comment]
Hi @niksy,

Do you have any timeframe for supporting second parameter?

Also there seems to be some progression in what Error constructor can consume: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error

**Comment by niksy** [comment]
@char0n I’ve added support for options like in original article, but every other option is non-standard so I would rather ignore it.

**Comment by char0n** [comment]
Yep, thanks. In my particular case it was about supporting the options param so that I could pass the `options.cause` inside the new error
